### ISSUE TITLE
Backend PSQL

### ISSUE THREAD

**Issue by artem00475** [Levit104/mobile-backend#1]
Сделать все эндпоинты к сервисы PSQL

**Comment by Levit104** [comment]
Fixed in 73b72be73303507c6d26b37f691d1b6f78ce9d27

**Comment by artem00475** [comment]
@Levit104 
1. Device routing:
- При добавлении устройства, искать типы состояния для этого типа устройства и создавать состояния с 0 значениями
- Удаление устройства + каскадное удаление связей
- При get запросе устройства добавить к выводу список состояний и действий
2. Action Routing:
- Поменять метод post: по действию нужно найти состояние объекта, и обновить его значение
3. Room Routing:
- Удаление комнаты + замена связей на null

**Comment by Levit104** [comment]
Исправил в b96df242126eac4766723d78d61149f959425e9c

**Comment by Levit104** [comment]
Исправил в b96df242126eac4766723d78d61149f959425e9c
