### ISSUE TITLE
Tester Service

### ISSUE THREAD

**Issue by artem00475** [Levit104/mobile-backend#6]

**Comment by artem00475** [comment]
@Levit104 сейчас есть метод входа и регистрации. Нужно сделать методы:

1) Добавление комнаты

2) Добавление устройства (получить список комнат, если комнат нет, то создать новую, иначе выбираем рандомно одну; получить типы устройств, выбрать рандомно один; отправить запрос на создание)

3) Удаление устройства (получаем список устройств, удаляем рандомно одно)

4) Удаление комнаты (получаем список комнат, удаляем одну рандомно)

5) Выполнение действия (получение списка устройств, выбор одного рандомно; получение списка действий по типу устройства, выбор одного рандомно; если есть параметр, то генерация параметра; для действия без параметра у нас будет передаваться true или false, соответственно нужно в запрос передать инверсное текущему значению.

Из этих действий вход и регистрация выполняются всегда, остальные должны выполняться в рандомном порядке и количестве.

**Comment by Levit104** [comment]
Доделали в b1b318a317341410ebf81ff5945296748b6774df
